<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-ML/blob/main/04_Lab1St.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Assignment 1 & Submit**

#A. Loading Dataset from ScikitLearn

###Step 1: Load the iris dataset from ScikitLearn and assign it to X and y variables:

In [2]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()

X = iris_dataset['data']
y = iris_dataset['target']

We import the load_iris function from the sklearn.datasets module to load the Iris dataset. Then, we assign the feature data to X and the target values to y.

###Step 2: Print the dataset keys using iris_dataset.keys():

In [3]:
print(iris_dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


We print the keys of the iris_dataset dictionary to see what information is stored in it.

###Step 3: Print the names of the categories in the target file:

In [4]:
print(iris_dataset['target_names'])

['setosa' 'versicolor' 'virginica']


We print the target names to see the different classes of the Iris dataset.

###Step 4: Print the feature names in the Iris dataset:

In [5]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


We print the feature names to see what are the different features in the Iris dataset.

###Step 5: Print the type of the Iris dataset:

In [6]:
print(type(iris_dataset))

<class 'sklearn.utils._bunch.Bunch'>


We print the type of iris_dataset to check if it's a dictionary.

###Step 6: Print the shape of the Iris dataset.

In [7]:
print(X.shape)

(150, 4)


We print the shape of the feature data to see how many samples and features are in the Iris dataset.

###Step 7: Print the first five rows of the Iris dataset.

In [8]:
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


We print the first five rows of the feature data to see what the data looks like.



###Step 8: Print the type of the target variable of Iris dataset.

In [9]:
print(type(y))

<class 'numpy.ndarray'>


We print the type of the target variable to check if it's a NumPy array.

###Step 9: Print the shape of the target variable of Iris dataset.

In [10]:
print(y.shape)

(150,)


We print the shape of the target variable to see how many target values are in the Iris dataset.

###Step 10: Print the entire target variable values of the Iris dataset.

In [11]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


We print the target variable to see what are the target values in the Iris dataset.

Step 11: Import NumPy with import numpy as np and use the numpy.unique() function to print the unique values of the target variable of Iris dataset

In [12]:
import numpy as np

print(np.unique(y))

[0 1 2]


We import NumPy as np and use its unique() function to see the unique values of the target variable.

###Step 12: Split dataset into train and test datasets using from sklearn.model_selection import train_test_split

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

We import the train_test_split() function from the sklearn.model_selection module to split the Iris dataset into training and testing sets. We use a random_state value of 0

###Step 13: Print the shape of train/test datasets and the train/test target variables.

In [14]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


###Step 14: Build your K-neighbors classifier for nearest neighbor of 1 using from sklearn.neighbors import KNeighborsClassifier, fit the model to your train dataset and make a prediction for teh data point of [5, 1.9, 1, 0.2]. Print your prediction class value as an integer and also the corresponding string label.

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np

# Step 1: Load iris dataset from ScikitLearn
iris_dataset = load_iris()
X = iris_dataset.data
y = iris_dataset.target

# Step 12: Split dataset into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Step 14: Build K-neighbors classifier for nearest neighbor of 1
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

# Make a prediction for the data point [5, 1.9, 1, 0.2]
X_new = np.array([[5, 1.9, 1, 0.2]])
prediction = knn.predict(X_new)
print("Prediction class value: ", prediction[0])
print("Corresponding string label: ", iris_dataset.target_names[prediction[0]])

Prediction class value:  0
Corresponding string label:  setosa


we use the KNeighborsClassifier class from scikit-learn to build a k-nearest neighbors model with a value of n_neighbors set to 1. This means that the model will predict the class of a new data point based on the class of its nearest neighbor in the training set.

We then fit the model to our training data using the fit method of the KNeighborsClassifier class.

Next, we create a new data point X_new containing the values [5, 1.9, 1, 0.2], which represents a new iris flower that we want to predict the species of.

We then use the predict method of the KNeighborsClassifier class to make a prediction for this new data point based on the trained model. The predicted class value is stored in the prediction variable.

Finally, we print the predicted class value and the corresponding string label for the predicted iris species using the target_names attribute of the iris_dataset object.

In this case, the predicted class value is 0, which corresponds to the 'setosa' species of iris, and this is confirmed by printing the corresponding string label as 'setosa'.





