<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-ML/blob/main/AA_4_01_LogisticReg_LinearSVMSt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["savefig.dpi"] = 300
plt.rcParams['savefig.bbox'] = 'tight'

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### 1. Load the cancer data set and check its size

### 2. Form train and test dasets and scale the data

### 3. Fit logistic regression to the first two features of your dataset

### 4. Create a scatter plot for the first two features of the train data set and draw the classification line on the graph

Let us pick two points $(x_{00},x_{10})$ and $(x_{01},x_{11})$ on the line $c_0x_0+c_1x_1+b=0$

Let us show these two points on the line:

\begin{align*}
c_0x_{00}+c_1x_{10}&=-6\\
c_0x_{01}+c_1x_{11}&=-6
\end{align*}
Let us subtract the second euation from the first, then we have $(c_0, c_1)\cdot (x_{01}-x_{00}, x_{10}-x_{11})=0$. $(x_{01}-x_{00}, x_{10}-x_{11})$ represents a vector on the line.

### 5. Create a toy dataset using Scikitlearn's make_blobs function.
- Use random_state=4
- Fit LogisticRegression() for C=0.1, 1, 100
- Plot the data on three figures and plot the classification line for each C value.

# Multiclass
- Load Iris dataset with `load_iris`
- check the shape and number of unique classes
- Fit Logistic regression and Linear SVC on the dataset
- Print the coefficients
- Print the intercept

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
X,y = iris.data, iris.target

In [7]:
X.shape

(150, 4)

In [8]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
import numpy as np
np.bincount(y)

array([50, 50, 50])

In [10]:
import pandas as pd
pd.value_counts(y)

0    50
1    50
2    50
dtype: int64

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
logreg = LogisticRegression(max_iter=4000)
logreg.fit(X,y)
logreg.coef_.shape

(3, 4)

In [13]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

[w11 w12 w13 w14]

[w21 w22 w23 w24]

[w31 w32 w33 w34]

In [14]:
#coef = logreg.coef_

In [15]:
X_new =X[0]#.reshape[1,4]

In [16]:
X_new

array([5.1, 3.5, 1.4, 0.2])

In [17]:
X_new.shape

(4,)

In [18]:
logreg.predict(X_new.reshape([1,4]))

array([0])

In [19]:
#intercept = logreg.intercept_

In [20]:
intercept = logreg.intercept_
coef = logreg.coef_

In [21]:
X_new.reshape([1,4])

array([[5.1, 3.5, 1.4, 0.2]])

In [22]:
X_new*coef[0]

array([-2.15840461,  3.38422878, -3.52342557, -0.21615469])

In [23]:
np.dot(X_new, coef[0]+intercept[0])
## intercept[0]+X_new[0]*coef[0,0]+X_new[1]*coef[0,1]+
##X_new[2]*coef[0,2]+X_new[3]*coef[0,3]


97.9488863525023

In [24]:
print(np.dot(X_new, coef[0])+intercept[0]) #class 0 vs (clas 1 and class2)
print(np.dot(X_new, coef[1])+intercept[1]) #class 1 vs (clas 0 and class2)
print(np.dot(X_new, coef[2])+intercept[2]) #class 2 vs (clas 0 and class1)

7.335522578392547
3.3595978570267784
-10.695120435419158


In [25]:
coef[0]

array([-0.42321659,  0.96692251, -2.51673255, -1.08077345])

In [26]:
#X_new[0]*coef[0,0]+X_new[1]*coef[0,1]+

In [ ]:
logreg.predict_proba(X_new)

In [28]:
logreg.predict_proba(X_new.reshape([1,4]))

array([[9.81583570e-01, 1.84164159e-02, 1.44983478e-08]])

In [29]:
import math

In [30]:
math.exp(-7.335522578392547) /1+((math.exp(7.335522578392547) + math.exp(-3.3595978570267784) + math.exp(-10.695120435419158)))

1533.86454034515

In [31]:
math.exp(-7.3355)/1+(-7.3355-10.6+3.35995)

-14.574898022170204

In [32]:
np.exp(-7.33)/(1+(np.exp(-(7.335+3.359-10.695))))

0.0003276229001797241

In [33]:
1/(1+(np.exp(-(7.335))))

0.9993481213227845

In [34]:
1/(1+(np.exp(-(3.359))))

0.966398319251531

In [35]:
logreg.decision_function(X_new.reshape([1,4]))

array([[  7.33552258,   3.35959786, -10.69512044]])