<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-ML/blob/main/AA_4_01_LogisticReg_LinearSVMSt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["savefig.dpi"] = 300
plt.rcParams['savefig.bbox'] = 'tight'

In [25]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
import math
math.log(10)

2.302585092994046

In [4]:
math.log(math.e)

1.0

In [5]:
math.log(100000)

11.512925464970229

In [6]:
math.log(0)

ValueError: ignored

In [ ]:
math.log(-2)

In [7]:
math.log(0.0000002)

-15.424948470398375

In [8]:
math.log(0.100000)

-2.3025850929940455

In [9]:
1/(1+math.log(10000))

0.09793992791314289

a data point y_i=1

x1=3, x2=4

we trained a model, the model coefficient are: w1=0.5, w2=1, w0=3.2

In [10]:
#a data point y_i=1
x1=3
x2=4

#we trained a model, the model coefficient are:
w1=0.5
w2=1
w0=3.2

dec_func_val=w0 + x1*w1 + x2*w2

In [11]:
dec_func_val

8.7

In [12]:
import numpy as np
print(dec_func_val)
yhat = np.sign(dec_func_val)
print(yhat)

8.7
1.0


In [13]:
#use the sigmoid fuction to compute the probability 0f the decision being right
p=1/(1+math.exp(-dec_func_val)) #this is probability that decision is yhat=1
print(p)

0.9998334419352227


In [18]:
#a data point y_i=1
x1=3
x2=4

#we trained a model, the model coefficient are:
w1=-0.5
w2=-1
w0=3.2

dec_func_val= w0 + x1*w1 + x2*w2

In [19]:
dec_func_val

-2.3

In [20]:
import numpy as np
print(dec_func_val)
yhat = np.sign(dec_func_val)
print(yhat)

-2.3
-1.0


In [21]:
#use the sigmoid fuction to compute the probability 0f the decision being right
p=1/(1+math.exp(-dec_func_val)) #this is probability that decision is yhat=1
print(p)

0.09112296101485616


In [22]:
p=1/(1+math.exp(-0.5))
print(p)

0.6224593312018546


In [23]:
p=1/(1+math.exp(0))
print(p)

0.5


In [ ]:

#you develop a model to detect cancer 

#most of the tue labels corresponding to cases where p>0.2 are actually 1, cancer.

### 1. Load the cancer data set and check its size

In [27]:
cancer = load_breast_cancer()
X, y = cancer.data, cancer.target

### 2. Form train and test dasets and scale the data

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y)

In [29]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### 3. Fit logistic regression to the first two features of your dataset

In [30]:
logreg = LogisticRegression(solver='liblinear')

In [31]:
logreg.fit(X_train[:,:2], y_train)

LogisticRegression(solver='liblinear')

In [35]:
print(logreg.score(X_train[:,:2], y_train))
print(logreg.score(X_test[:,:2], y_test))

0.8943661971830986
0.8741258741258742


In [41]:
logreg.coef_

array([[-3.19370233, -0.79121372]])

In [37]:
logreg.coef_

array([[-3.19370233, -0.79121372]])

In [43]:
w0=logreg.intercept_
w0

array([0.65876117])

### 4. Create a scatter plot for the first two features of the train data set and draw the classification line on the graph

Let us pick two points $(x_{10},x_{11})$ and $(x_{21},x_{22})$ on the line $w_1x_1+w_2x_2+w0=0$

Let us show these two points on the line:

\begin{align*}
w_1x_{10}+c_2x_{20}&=-6\\
w_1x_{21}+w_2x_{21}&=-6
\end{align*}
Let us subtract the second euation from the first, then we have $(c_0, c_1)\cdot (x_{01}-x_{00}, x_{10}-x_{11})=0$. $(x_{01}-x_{00}, x_{10}-x_{11})$ represents a vector on the line.

In [46]:
coef = logreg.coef_
coef.shape

(1, 2)

In [47]:
coef

array([[-3.19370233, -0.79121372]])

In [51]:
coef[0][0]

-3.1937023336490085

In [52]:
coef[0][1]

-0.7912137185796769

In [54]:
coef = logreg.coef_.ravel()
coef.shape

(2,)

In [55]:
coef[1]

-0.7912137185796769

In [59]:
import numpy as np
xmin, xmax = -4,4
xx=np.linspace(xmin,xmax,100)
xx

array([-4.        , -3.91919192, -3.83838384, -3.75757576, -3.67676768,
       -3.5959596 , -3.51515152, -3.43434343, -3.35353535, -3.27272727,
       -3.19191919, -3.11111111, -3.03030303, -2.94949495, -2.86868687,
       -2.78787879, -2.70707071, -2.62626263, -2.54545455, -2.46464646,
       -2.38383838, -2.3030303 , -2.22222222, -2.14141414, -2.06060606,
       -1.97979798, -1.8989899 , -1.81818182, -1.73737374, -1.65656566,
       -1.57575758, -1.49494949, -1.41414141, -1.33333333, -1.25252525,
       -1.17171717, -1.09090909, -1.01010101, -0.92929293, -0.84848485,
       -0.76767677, -0.68686869, -0.60606061, -0.52525253, -0.44444444,
       -0.36363636, -0.28282828, -0.2020202 , -0.12121212, -0.04040404,
        0.04040404,  0.12121212,  0.2020202 ,  0.28282828,  0.36363636,
        0.44444444,  0.52525253,  0.60606061,  0.68686869,  0.76767677,
        0.84848485,  0.92929293,  1.01010101,  1.09090909,  1.17171717,
        1.25252525,  1.33333333,  1.41414141,  1.49494949,  1.57

In [58]:
#import numpy as np
#xmin, xmax = X_train[:,1].min(), X_train[:,1].max()
#xx=np.linspace(xmin,xmax)
#xx

In [ ]:
wx+b=0

w1*x1 + w2*x2 + b

### 5. Create a toy dataset using Scikitlearn's make_blobs function.
- Use random_state=4
- Fit LogisticRegression() for C=0.1, 1, 100
- Plot the data on three figures and plot the classification line for each C value.

# Multiclass
- Load Iris dataset with `load_iris`
- check the shape and number of unique classes
- Fit Logistic regression and Linear SVC on the dataset
- Print the coefficients
- Print the intercept