<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-ML/blob/main/AA_4_01_LogisticReg_LinearSVMSt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["savefig.dpi"] = 300
plt.rcParams['savefig.bbox'] = 'tight'

In [4]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### 1. Load the cancer data set and check its size

### 2. Form train and test dasets and scale the data

### 3. Fit logistic regression to the first two features of your dataset

### 4. Create a scatter plot for the first two features of the train data set and draw the classification line on the graph

Let us pick two points $(x_{00},x_{10})$ and $(x_{01},x_{11})$ on the line $c_0x_0+c_1x_1+b=0$

Let us show these two points on the line:

\begin{align*}
c_0x_{00}+c_1x_{10}&=-6\\
c_0x_{01}+c_1x_{11}&=-6
\end{align*}
Let us subtract the second euation from the first, then we have $(c_0, c_1)\cdot (x_{01}-x_{00}, x_{10}-x_{11})=0$. $(x_{01}-x_{00}, x_{10}-x_{11})$ represents a vector on the line.

### 5. Create a toy dataset using Scikitlearn's make_blobs function.
- Use random_state=4
- Fit LogisticRegression() for C=0.1, 1, 100
- Plot the data on three figures and plot the classification line for each C value.

# Multiclass
- Load Iris dataset with `load_iris`
- check the shape and number of unique classes
- Fit Logistic regression and Linear SVC on the dataset
- Print the coefficients
- Print the intercept

In [5]:
from sklearn.datasets import load_iris

In [6]:
iris = load_iris()

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
X,y = iris.data, iris.target

In [9]:
X.shape

(150, 4)

In [10]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
import numpy as np
np.bincount(y)

array([50, 50, 50])

In [13]:
import pandas as pd
pd.value_counts(y)

0    50
1    50
2    50
dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logreg = LogisticRegression(max_iter=4000)
logreg.fit(X,y)
logreg.coef_.shape

(3, 4)

In [16]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])