<a href="https://colab.research.google.com/github/ArifAygun/Magnimind-ML/blob/main/AA_Supervised_learning_St.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Check Version of the Relevant Libraries

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import scale

In [2]:
cancer = load_breast_cancer()

In [3]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
X = cancer.data
y = cancer.target
X = scale (X)

In [5]:
import numpy as np
np.unique(y, return_counts=True)

(array([0, 1]), array([212, 357]))

In [6]:
X_trainval, X_test, y_trainval, y_test = train_test_split(X, y)

In [7]:
sum(y_trainval)/len(y_trainval), sum(y_test)/len(y_test)

(0.6244131455399061, 0.6363636363636364)

In [8]:
X_trainval, X_test, y_trainval, y_test = train_test_split(X, y, stratify=y)

In [9]:
sum(y_trainval)/len(y_trainval), sum(y_test)/len(y_test)

(0.6267605633802817, 0.6293706293706294)

In [10]:
X_train, X_val, y_train, y_val = train_test_split(X,y, stratify=y)

In [11]:
X_train, X_val, y_train, y_val = train_test_split(X_trainval,y_trainval, stratify=y_trainval)

In [12]:
sum(y_trainval)/len(y_trainval), sum(y_test)/len(y_test),\
sum(y_train)/len(y_train), sum(y_val)/len(y_val)

(0.6267605633802817,
 0.6293706293706294,
 0.6269592476489029,
 0.6261682242990654)

In [13]:
knn1 = KNeighborsClassifier() # default number of neighbors is 5

In [14]:
knn1 = KNeighborsClassifier(n_jobs=5)
knn2 = KNeighborsClassifier(n_jobs=5)

In [15]:
knn1.fit(X_train, y_train)

KNeighborsClassifier(n_jobs=5)

In [16]:
knn1.score(X_val, y_val)

0.9626168224299065

In [17]:
knn1.score(X_test,y_test)

0.965034965034965

In [18]:
knn1.score(X_train, y_train)

0.9780564263322884

In [19]:
import numpy as np

In [20]:
np.array([1,3,4,7,9,11,13])

array([ 1,  3,  4,  7,  9, 11, 13])

In [21]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [22]:
val_scores = [] #validation scores
neighbors = np.arange (1,15,2)

for i in neighbors:
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train, y_train)
  s = knn.score(X_val, y_val)
  val_scores.append(s)

print('best validation score is : {:.2f}'.format(np.max(val_scores)))
best_n_neighbors = neighbors[np.argmax(val_scores)]
print('best n_neighbors is : {:.2f}'.format(neighbors[np.argmax(val_scores)]))

best validation score is : 0.96
best n_neighbors is : 1.00


In [23]:
knn3 = KNeighborsClassifier(n_neighbors = best_n_neighbors)

knn3.fit(X_trainval, y_trainval)

KNeighborsClassifier(n_neighbors=1)

In [24]:
knn3.score(X_test, y_test)

0.9790209790209791

In [25]:
val_scores

[0.9626168224299065,
 0.9626168224299065,
 0.9626168224299065,
 0.9626168224299065,
 0.9626168224299065,
 0.9532710280373832,
 0.9439252336448598]

In [26]:
np.max(val_scores), np.argmax(val_scores), neighbors[np.argmax(val_scores)]

(0.9626168224299065, 0, 1)

In [27]:
knn4 = KNeighborsClassifier(n_neighbors = 11)

knn4.fit(X_trainval, y_trainval)

knn4.score(X_test, y_test)

0.965034965034965

# Overfitting the test set

- Import `breast_cancer` dataset from Scikitlearn
- Scale the feature set
- Split data into first trainval and test, then split trainval into validation and train datasets
- Fit train dataset for `k=5` neighbors
- print the score on validation and test datasets

- Create a loop and fit your train dataset and test your validation dataset for `k=1,15,2`.
- Print the best validation score out of three neighbors and determine the `k` value with the highest score, $best_n$
- Retrain your model with trainvalidation dataset for $k=best_n$
- Print the score for test dataset for the latest trained model

# Cross validation

- Import `cross_val_score` from `sklearn.model_selection`
- Split your data into train and test datasets
- For `neighbors=1, 15, 2`, compute cross validation scores for trainvalidation dataset with kfold=10.
- Print the best validation score out of three neighbors and determine the `k` value with the highest score, $best_n$
- Retrain your model with trainvalidation dataset for $k=best_n$
- Print the score for test dataset for the latest trained model

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y)

In [31]:
neighbors = np.arange(1,15,2)
cross_val_scores = []

for i in neighbors:
  print('n_neighbors: {}'.format(i))
  knn = KNeighborsClassifier(n_neighbors=i)
  scores = cross_val_score(knn, X_train, y_train, cv=5)
  print(scores)
  cross_val_scores.append(np.mean(scores))

print('best validation score is : {:.2f}'.format(np.max(cross_val_scores)))
best_n_neighbors = neighbors[np.argmax(cross_val_scores)]
print('best n_neighbors is : {:.2f}'.format(neighbors[np.argmax(cross_val_scores)]))  

n_neighbors: 1
[0.97 0.93 0.98 0.95 0.98]
n_neighbors: 3
[0.97 0.95 0.99 0.98 0.98]
n_neighbors: 5
[0.97 0.95 0.98 0.98 0.96]
n_neighbors: 7
[0.98 0.95 0.99 0.96 0.94]
n_neighbors: 9
[0.98 0.95 0.98 0.96 0.93]
n_neighbors: 11
[0.98 0.94 0.99 0.96 0.93]
n_neighbors: 13
[0.98 0.95 0.98 0.95 0.93]
best validation score is : 0.97
best n_neighbors is : 3.00


- Compute cross validation score for `KNeighborsClassifier()` when `cv=KFold(n_splits=5)` and `cv=StratifiedKFold(n_splits=5, shuffle=True)`

In [28]:
np.set_printoptions(precision=2)

# GridSearchCV

- Import `GridSearchCV` from `sklearn.model_selection`
- Split your data into train and test datasets
- For `neighbors=1 to 30`, compute `GridSearchCV` for train dataset with kfold=10.
- Print the best cross validation score 
- Priont the best parameter
- Print the test score

Instead of above for loops
we can do the same process with GridSearch

In [33]:
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y)

mygridval = {'n_neighbors': np.arange(1,15,2)}

In [37]:
from sklearn.model_selection import StratifiedGroupKFold
#knn = KNeighborsClassifier
cv = StratifiedGroupKFold(n_splits=5)
mygrid = GridSearchCV(KNeighborsClassifier(), param_grid=mygridval, cv=5, return_train_score=True)

In [41]:
mygrid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13])},
             return_train_score=True)

In [39]:
mygrid.best_score_

0.9600820793433653

In [40]:
mygrid.best_params_

{'n_neighbors': 13}